// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShopMvcApp_PV212.Data;

#nullable disable

namespace ShopMvcApp_PV212.Migrations
{
    [DbContext(typeof(ShopDbContext))]
    [Migration("20240705172203_AddArchivedFlag")]
    partial class AddArchivedFlag
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ShopMvcApp_PV212.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Electronics"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Sport"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Fashion"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Home & Garden"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Transport"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Toys & Hobbies"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Musical Instruments"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Art"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Other"
                        });
                });

            modelBuilder.Entity("ShopMvcApp_PV212.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Archived")
                        .HasColumnType("bit");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Discount")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Archived = false,
                            CategoryId = 1,
                            Discount = 10,
                            Name = "iPhone X",
                            Price = 650m,
                            Quantity = 5
                        },
                        new
                        {
                            Id = 2,
                            Archived = false,
                            CategoryId = 2,
                            Discount = 0,
                            Name = "PowerBall",
                            Price = 45.5m,
                            Quantity = 3
                        },
                        new
                        {
                            Id = 3,
                            Archived = false,
                            CategoryId = 3,
                            Discount = 15,
                            Name = "Nike T-Shirt",
                            Price = 189m,
                            Quantity = 3
                        },
                        new
                        {
                            Id = 4,
                            Archived = false,
                            CategoryId = 1,
                            Discount = 5,
                            Name = "Samsung S23",
                            Price = 1200m,
                            Quantity = 0
                        },
                        new
                        {
                            Id = 5,
                            Archived = false,
                            CategoryId = 6,
                            Discount = 0,
                            Name = "Air Ball",
                            Price = 50m,
                            Quantity = 0
                        },
                        new
                        {
                            Id = 6,
                            Archived = false,
                            CategoryId = 1,
                            Discount = 10,
                            Name = "MacBook Pro 2019",
                            Price = 0m,
                            Quantity = 23
                        },
                        new
                        {
                            Id = 7,
                            Archived = false,
                            CategoryId = 2,
                            Discount = 0,
                            Name = "Samsung S4",
                            Price = 440m,
                            Quantity = 0
                        });
                });

            modelBuilder.Entity("ShopMvcApp_PV212.Entities.Product", b =>
                {
                    b.HasOne("ShopMvcApp_PV212.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("ShopMvcApp_PV212.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
